---
on:
  push:
    branches:
      - master
      - main
  pull_request: ~
name: molecule test & semantic-release
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Install python
        uses: actions/setup-python@v4.1.0

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install python packages
        run: pip install --no-input --requirement mol_requirements.txt

      - name: Full molecule test
        run: molecule test
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
          MOL_DRIVER: docker

      - name: Install nodejs
        if: github.event_name == 'push'
        uses: actions/setup-node@v2

      - name: Install npm packages
        if: github.event_name == 'push'
        run: npm install

      - name: Create new release
        if: github.event_name == 'push'
        run: npx semantic-release
        env:
          GIT_AUTHOR_NAME: ${{ github.actor }}
          GIT_AUTHOR_EMAIL: ${{ github.actor }}@users.noreply.github.com
          GIT_COMMITTER_NAME: ${{ github.actor }}
          GIT_COMMITTER_EMAIL: ${{ github.actor }}@users.noreply.github.com
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ANSIBLE_GALAXY_API_KEY: ${{ secrets.ANSIBLE_GALAXY_API_KEY }}
